# Generated by Django 5.0.1 on 2024-01-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.BooleanField(choices=[('SEARCHING', 'Поиск команды'), ('RECRUITING', 'Набор в команду')], db_index=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('needed_players', models.IntegerField(blank=True)),
                ('team_logo', models.ImageField(blank=True, upload_to='photos/searchteam/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
    ]
