

volumes:
  postgres_data:

services:
  db:
    image: postgres:15-alpine
    container_name: socialnetwork-db
    ports:
      - 5432:5432
    environment: # установка переменных окружения
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  socialnetwork:
    build: ./socialnetwork
    ports:
      - 8000:8000
    volumes:
      - ./socialnetwork:/service
    env_file: ./socialnetwork/socialnetwork/.env
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    container_name: socialnetwork-service
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.2.3-alpine
    container_name: socialnetwork-redis

  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    container_name: socialnetwork-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s

  celery:
    build: ./socialnetwork
    container_name: socialnetwork-celery
    volumes:
      - ./socialnetwork:/service
    env_file: ./socialnetwork/socialnetwork/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db: 
        condition: service_started
      redis: 
        condition: service_started
      socialnetwork: 
        condition: service_started


    command: celery -A socialnetwork worker --loglevel=info --beat



  
